
GET http://localhost:3000/actors
###
GET http://localhost:3000/actors/2
###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "",
  "last_name": "",
  "known_for": "",
  "gender": "",
  "age": 2
}
###
PATCH http://localhost:3000/actors/6
Content-Type: application/json

{
  "gender": "male",
  "age": 12
}

###
DELETE http://localhost:3000/actors/7
###
GET http://localhost:3000/movies
###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "",
  "year": "",
  "plot": "",
  "director": "",
  "english": true
}
###
PATCH http://localhost:3000/movies/3
Content-Type: application/json

{
  "director": ""
}

###
DELETE http://localhost:3000/movies/5
###
