
GET http://localhost:3000/movies
###
GET http://localhost:3000/movies/2
###

POST http://localhost:3000/movies/create
Content-Type: application/json

{
  "first_name": "Will",
  "last_name": "Farrell",
  "known_for": "Talledega Nights"
}
###
PATCH http://localhost:3000/movies/7
Content-Type: application/json

{
  "known_for": "Elf"
}

###
DELETE http://localhost:3000/movies/7
###
GET http://localhost:3000/movies
###

POST http://localhost:3000/movies/create
Content-Type: application/json

{
  "title": "Gone With the Wind",
  "year": "1940",
  "plot": "A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods."
}
###
PATCH http://localhost:3000/movies/5
Content-Type: application/json

{
  "year": "1939"
}

###
DELETE http://localhost:3000/movies/5
###
